### PR TITLE
Use CSS to position expanded tile content

### PR DESCRIPTION
**Pull request by spadgett**

### CODE REVIEW

**Comment by spadgett** [comment]
@dtaylor113 PTAL

**Comment by dtaylor113** [comment]
Hi @spadgett, could you include a screenshot? -thanks

**Comment by dtaylor113** [comment]
Hi @spadgett,  I appreciate the CSS clean-up.  However, I think some work still needs to be done.   As you mentioned, the margin-bottom of the active card is fixed, so for one row expansion cards, there is a significant gap:

image

Do you envision adding back the calculations which dynamically set the margin-bottom of the active card?
Thanks,
Dave

**Comment by dtaylor113** [comment]
Hi, I see you have comments in the less files "// TODO: Remove when sidebar is no longer fixed position."  -Just want to verify that once the sidebar is no longer fixed position that the scrollbar for the expansion card will be positioned correctly:

image

Thanks!

**Comment by spadgett** [comment]
Pushed an update, PTAL

**Comment by dtaylor113** [comment]
Umm...I don't see any difference after the update?  I still see a large gap for single row expansion card.

**Comment by spadgett** [comment]
It's still a fixed height until the JS changes (although should be white)

**Comment by dtaylor113** [comment]
Hi, my previous PR also hid/covered the 'Other' sub-category card and put the expansion card directly under the main categories row:

image

I wasn't particularly happy with my solution so maybe we leave it and I figure out how to render correctly without the 'Other' sub-category being defined.

**Comment by dtaylor113** [comment]
I also have to ask @serenamarie125 about what to do when there is only one sub-category.  Doesn't seem like we should have an 'All' and a single sub-category.  I imagine 'All' should not be shown in this case.

image

**Comment by spadgett** [comment]
Updated with the JS fix for expanded row height. @dtaylor113 one more look? Thanks for your patience.

**Comment by spadgett** [comment]
I haven't made any changes for the other category

**Comment by spadgett** [comment]
Thanks @dtaylor113

**Pull request merged**
